export const COSTUMERS_LOADING = 'COSTUMERS_LOADING';
export const COSTUMERS_FAILED = 'COSTUMERS_FAILED';
export const ADD_COSTUMERS = 'ADD_COSTUMERS';
export const PAYMENTS_LOADING = 'PAYMENTS_LOADING';
export const PAYMENTS_FAILED = 'PAYMENTS_FAILED';
export const ADD_PAYMENTS = 'ADD_PAYMENTS';